console.log(2 == '2');
console.log(2 === '2');
console.log(2 + '2');
console.log(2 < '3');
console.log(true == '1');
console.log("10" - 2);
console.log(true + 2);
console.log(false == 0);
console.log([] == '');